### ISSUE TITLE
Not working in node.js version > 5.12.0 <v7.1.0 ??

### ISSUE THREAD

**Issue by stefanwalther** [verbose/verb#104]
Hi,

I have not been watching the repo for a while. Now I wanted to update and get weird error in node.js v6.8.0:

**v6.8.0:**
```sh
(node:92867) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
path.js:7
    throw new TypeError('Path must be a string. Received ' + inspect(path));
    ^

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.dirname (path.js:1324:5)
    at Liftoff.run (/usr/local/lib/node_modules/verb-cli/bin/verb.js:133:27)
    at Liftoff.<anonymous> (/usr/local/lib/node_modules/verb-cli/node_modules/liftoff/index.js:192:16)
    at module.exports (/usr/local/lib/node_modules/verb-cli/node_modules/liftoff/node_modules/flagged-respawn/index.js:17:3)
    at Liftoff.<anonymous> (/usr/local/lib/node_modules/verb-cli/node_modules/liftoff/index.js:185:9)
    at /usr/local/lib/node_modules/verb-cli/node_modules/liftoff/index.js:159:9
    at /usr/local/lib/node_modules/verb-cli/node_modules/v8flags/index.js:108:14
    at /usr/local/lib/node_modules/verb-cli/node_modules/v8flags/index.js:36:12
    at /usr/local/lib/node_modules/verb-cli/node_modules/v8flags/index.js:47:7
```

Strangely the same solution works in node.js v7.1.0 and v5.12.0.
In all cases I did a:

```sh
$ npm cache clear
npm install --global "verbose/verb#dev"
npm install verb-generate-readme -g
```

Any ideas?

**Comment by doowb** [comment]
Looks like that error is coming from `verb-cli` (which isn't needed with the verb dev branch).
Uninstall `verb-cli` and try reinstalling `verbose/verb#dev` like you did  before.
