### ISSUE TITLE
Exception when using the `example`-helper

### ISSUE THREAD

**Issue by nknapp** [verbose/verb#53]
I was trying to use the example helper to include example-code into the README.md
of [this project](https://github.com/nknapp/line-counter)
I get an exception and I do not see the reason.  Can you tell me what I am doing wrong?

The exception is:
```
TypeError: undefined is not a function
    at DestroyableTransform._transform (/home/nknappmeier/programs/node/node-v0.12.0-linux-x64/lib/node_modules/verb-cli/node_modules/verb/lib/plugins/dest.js:44:26)
    at DestroyableTransform.Transform._read (/home/nknappmeier/programs/node/node-v0.12.0-linux-x64/lib/node_modules/verb-cli/node_modules/verb/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (/home/nknappmeier/programs/node/node-v0.12.0-linux-x64/lib/node_modules/verb-cli/node_modules/verb/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:172:12)
    at doWrite (/home/nknappmeier/programs/node/node-v0.12.0-linux-x64/lib/node_modules/verb-cli/node_modules/verb/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:237:10)
    at writeOrBuffer (/home/nknappmeier/programs/node/node-v0.12.0-linux-x64/lib/node_modules/verb-cli/node_modules/verb/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:227:5)
    at DestroyableTransform.Writable.write (/home/nknappmeier/programs/node/node-v0.12.0-linux-x64/lib/node_modules/verb-cli/node_modules/verb/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:194:11)
    at Stream.method [as write] (/home/nknappmeier/programs/node/node-v0.12.0-linux-x64/lib/node_modules/verb-cli/node_modules/verb/node_modules/event-stream/node_modules/duplexer/index.js:47:39)
    at Stream.ondata (stream.js:51:26)
    at Stream.<anonymous> (/home/nknappmeier/programs/node/node-v0.12.0-linux-x64/lib/node_modules/verb-cli/node_modules/verb/node_modules/session-cache/node_modules/continuation-local-storage/context.js:74:17)
    at Stream.emit (events.js:107:17)
```

**Comment by jonschlinkert** [comment]
I think it's failing because of the `.txt` extension, sorry about that. when I created it my use case was to use working javascript examples. let me know if it doesn't work with just the javascript one.

**Comment by nknapp** [comment]
It also did not work if I removed the "example.txt" line completely. I have now written a small helper myself, which does work for me. I am still wondering. Is the `example`-helper doing the same thing or have I misunderstood the use-case:

```js
verb.asyncHelper("inline_file", function (filepath, next) {
    var filename = require.resolve(filepath)
    var moduleName = this.context.name;
    return fs.readFile(filename, 'utf8', function(err, contents) {
        if (err) {
            return next(err);
        }
        // This is the module-name that is used by the example file, when
        // requiring the current module
        var requirePattern = path.relative(path.dirname(filename),__dirname);
        var requireRegex = new RegExp("require\\([\'\"]"+requirePattern+"/?[\'\"]\\)","g");
        next(null,contents.replace(requireRegex,"require('"+moduleName+"')"));
    });
});
```

**Comment by jonschlinkert** [comment]
> I am still wondering. Is the example-helper doing the same thing or have I misunderstood the use-case:

I've been using it to just include a javascript snippet from `example.js`. Since `example.js` is supposed to demonstrate working code (for my use case), the only additional thing the helper does is replace

```js
var foo = require('./');
```
with

```js
var foo = require('foo');
```

So that it makes sense from the frame of reference of a readme example. which is what you're doing as well.

My only feedback is that it might be easier/less code to register as a sync helper. The only reason I register it as async is to use `async-helper-base` 1) since it's already there, and 2) since I'm pre-loading the javascript files so they can be pulled off the `views` object as templates. Really, that's not necessary, the way you're doing it looks great too

**Comment by nknapp** [comment]
Well, now that you mention `var foo = require('./');`: The `example` helper *does* work, if the example file is in the project's root-directory.

**Comment by jonschlinkert** [comment]
you might be able to change the cwd by passing it to the helper:

```js
{%= example("foo", {cwd: "bar") %}
```

**Comment by nknapp** [comment]
OK, but when I have an example in a subdirectory of the project, I have to do `require('../')` instead of `require('./')`, so the example-helper won't substitute the module name.

However, I was wondering, how the whole helper setup in verb works. I was trying to figure out what to do from the code, but [the source code of the example helper](https://github.com/assemble/verb/blob/master/lib/helpers/custom/example.js) looks like it would just return the string (which in my understanding would be the filename) in a slightly modified form. I came across some more complex files when using a debugger, but I couldn't really grasp the whole concept.
Could you write a little about that?

**Comment by jonschlinkert** [comment]
> so the example-helper won't substitute the module name.

```js
{%= replace(example("foo", {cwd: "../"), "../", name) %}
```

**Comment by nknapp** [comment]
Is there a list of helpers that can be used with verb without including any other packages?

**Comment by jonschlinkert** [comment]
let me know if this helps! https://github.com/verbose/verb/commit/892cee09c0bc4476985aaf1695f4e3a6d993d7b9

**Comment by nknapp** [comment]
Looks great, thanks

**Comment by jonschlinkert** [comment]
no prob, happy to help

**Comment by nknapp** [comment]
Just to let you know. I change the verb-template of `line-counter` to use 
```
{%= embed("./examples/example.txt") %}
```
and
```
{%= replace(embed("./examples/regex-matches.js"),"../",name) %}
```
Now there is no need for a `verbfile.js` and custom helpers anymore.
I like verb... It's exactly what I was looking for. Sadly, it took a while to find it...

**Comment by jonschlinkert** [comment]
Awesome!
