### ISSUE TITLE
moment.locale deprecated in verb dep

### ISSUE THREAD

**Issue by phun-ky** [verbose/verb#77]
Getting this error:

I'm getting this error:

    Deprecation warning: moment.lang is deprecated. Use moment.locale instead.
    Error
    at Function.lang (/../../node_modules/moment/moment.js:746:36)
    at Object.exports.date (/../../node_modules/gulp-verb/node_modules/verb/lib/tags/moment.js:22:12)
    at eval (eval at template (/../../node_modules/gulp-verb/node_modules/lodash/dist/lodash.js:6306:22), <anonymous>:8:11)
    at Function.template (/../../node_modules/gulp-verb/node_modules/lodash/dist/lodash.js:6312:16)
    at template (/../../node_modules/gulp-verb/node_modules/verb/node_modules/template/index.js:36:15)
    at Object.module.exports [as template] (/../../node_modules/gulp-verb/node_modules/verb/lib/template.js:27:10)
    at Object.tags.docs (/../../node_modules/gulp-verb/node_modules/verb/lib/tags/docs.js:58:23)
    at eval (eval at template (/../../node_modules/gulp-verb/node_modules/lodash/dist/lodash.js:6306:22), <anonymous>:42:11)
    at Function.template (/../../node_modules/gulp-verb/node_modules/lodash/dist/lodash.js:6312:16)
    at template (/../../node_modules/gulp-verb/node_modules/verb/node_modules/template/index.js:36:15)

Please update deps, posted on gulp-verb aswell: https://github.com/verbose/gulp-verb/issues/6

**Comment by jonschlinkert** [comment]
this is a gulp verb issue. closing here
