### ISSUE TITLE
0.9.0: loading helpers from verb config from package.json

### ISSUE THREAD

**Issue by tunnckoCore** [verbose/verb#92]
@jonschlinkert as you mention. I think it not works.

```json
"verb":
   "helpers": [
      "helper-simple-related"
    ],
}
```

in verb.md
```md
{%= simpleRelated(verb.related.list) %}
```
and it outputs the returned `simpleRelated` function (see below). I followed `helper-related` pattern - module exports that exports function which returns async function.

```js
module.exports = function (options) {
  return function simpleRelated (repos, opts, cb) {
    // code
    cb(null, res) // where `res` is the constructed string
  }
}
```

**Comment by jonschlinkert** [comment]
sorry, I forgot to mention async helpers. try using:

```json
"verb":
   "asyncHelpers": [
      "helper-simple-related"
    ],
}
```

**Comment by tunnckoCore** [comment]
Hmm, yea, make sense. Will try.

**Comment by tunnckoCore** [comment]
Nope. Not works.

```
[charlike@voltaire handle-arguments]$ verb
[03:22:50] starting readme generator
[03:22:50] starting readme:readme task
[03:22:50] starting readme generator
[03:22:50] finished readme generator 56ms
ReferenceError: simpleRelated is not defined
    at eval (engine.templateSources[1]:24:11)
    at /home/charlike/.nvm/versions/node/v5.8.0/lib/node_modules/verb/node_modules/engine-cache/index.js:201:17
    at Object.wrappedRender [as render] (/home/charlike/.nvm/versions/node/v5.8.0/lib/node_modules/verb/node_modules/engine-cache/index.js:256:7)
    at /home/charlike/.nvm/versions/node/v5.8.0/lib/node_modules/verb/node_modules/templates/lib/plugins/render.js:291:16
    at /home/charlike/.nvm/versions/node/v5.8.0/lib/node_modules/verb/node_modules/templates/lib/plugins/routes.js:133:7
    at /home/charlike/.nvm/versions/node/v5.8.0/lib/node_modules/verb/node_modules/en-route/lib/index.js:576:15
    at next (/home/charlike/.nvm/versions/node/v5.8.0/lib/node_modules/verb/node_modules/en-route/lib/index.js:161:14)
    at /home/charlike/.nvm/versions/node/v5.8.0/lib/node_modules/verb/node_modules/en-route/lib/index.js:183:18
    at Function.matchLayer (/home/charlike/.nvm/versions/node/v5.8.0/lib/node_modules/verb/node_modules/en-route/lib/index.js:264:3)
    at next (/home/charlike/.nvm/versions/node/v5.8.0/lib/node_modules/verb/node_modules/en-route/lib/index.js:164:10)
ENV: undefined
```

**Comment by jonschlinkert** [comment]
k thx. want to do a pr to base-runner? basically you can copy the logic used for `helpers` (don't worry about duplicating code, all of those fields are going to be refactored anyway)

**Comment by stefanwalther** [comment]
Are (non async) helpers supposed to work in current version of verb (0.9/dev)?

```js
"verb":
   "helpers": [
      "helper-simple-related"
    ],
}
```

**Comment by jonschlinkert** [comment]
sync helpers work in 0.9.0. there are many sync helpers used in verb-generate-readme, just make sure you're exporting the correct signature.
